(in-package #:org.shirakumo.fraf.mixed.examples)

(defun play (file &key (samplerate 44100) (buffersize 100)
                       (output 'org.shirakumo.fraf.mixed.out123:drain)
                       (input 'org.shirakumo.fraf.mixed.mpg123:source))
  (mixed:init)
  (mixed:with-objects ((source (mixed:make-unpacker :samplerate samplerate :frames buffersize))
                       (drain (mixed:make-packer :samplerate samplerate :frames buffersize))
                       (inp (make-instance input :file file :pack source))
                       (out (make-instance output :pack drain)))
    (mixed:with-buffers buffersize (l r)
      (mixed:connect source :left drain :left l)
      (mixed:connect source :right drain :right r)
      (mixed:start out)
      (mixed:with-chain chain (inp source drain out)
        (format T "~&Playing back on ~d channels @ ~dHz, ~a~%"
                (mixed:channels drain) (mixed:samplerate drain) (mixed:encoding drain))
        (loop until (mixed:done-p inp)
              do (mixed:mix chain))))))
